name: Deploy Frontend to S3

on:
  push:
    branches:
      - main
    paths:
      - 'index.html'
      - 'styles.css'
      - 'script.js'

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1
    
    - name: Create S3 bucket
      run: |
        aws s3 mb s3://medgenai-frontend-app --region us-east-1 || true
    
    - name: Upload files to S3
      run: |
        aws s3 sync . s3://medgenai-frontend-app --exclude "*" --include "*.html" --include "*.css" --include "*.js"
    
    - name: Configure S3 for static website
      run: |
        aws s3 website s3://medgenai-frontend-app --index-document index.html
    
    - name: Set public read policy
      run: |
        aws s3api put-bucket-policy --bucket medgenai-frontend-app --policy '{
          "Version": "2012-10-17",
          "Statement": [
            {
              "Sid": "PublicReadGetObject",
              "Effect": "Allow",
              "Principal": "*",
              "Action": "s3:GetObject",
              "Resource": "arn:aws:s3:::medgenai-frontend-app/*"
            }
          ]
        }'